[package]
name = "printers"
version = "1.0.0"
authors = ["Tales Luna <tales.ferreira.luna@gmail.com>"]
edition = "2018"

# [dependencies]
[dependencies.uuid]
version = "1.1.2"
features = [ "v4", "v5" ]

[lib]
bench = false
path = "src/lib.rs"
name = "printers"
